// Element Plus 常用图标
export const elementIcons = [
  'User', 'UserFilled', 'Setting', 'Tools', 'Monitor', 'View', 'Hide',
  'Document', 'Folder', 'FolderOpened', 'Files', 'Edit', 'EditPen',
  'Delete', 'Remove', 'Plus', 'Minus', 'Search', 'Refresh', 'Download',
  'Upload', 'Share', 'Star', 'StarFilled', 'Collection', 'CollectionTag',
  'Flag', 'Location', 'Position', 'Promotion', 'Rank', 'Trophy',
  'Medal', 'PriceTag', 'Discount', 'Coin', 'Money', 'Wallet',
  'CreditCard', 'Present', 'Box', 'Goods', 'ShoppingCart', 'ShoppingBag',
  'Sell', 'Sold', 'TakeawayBox', 'Dish', 'Bowl', 'KnifeFork',
  'Coffee', 'IceCream', 'Lollipop', 'Cherry', 'Apple', 'Orange',
  'Pear', 'Watermelon', 'Grape', 'Strawberry', 'Management', 'Operation',
  'Histogram', 'PieChart', 'DataLine', 'DataBoard', 'TrendCharts',
  'Grid', 'Menu', 'List', 'MoreFilled', 'More', 'Expand',
  'Fold', 'ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', 'Back',
  'Right', 'Top', 'Bottom', 'Sort', 'SortUp', 'SortDown',
  'Rank', 'Filter', 'Finished', 'CircleCheck', 'CircleClose', 'Close',
  'Check', 'CloseBold', 'Select', 'SemiSelect', 'Loading', 'Refresh',
  'RefreshLeft', 'RefreshRight', 'Switch', 'SwitchButton', 'Connection',
  'Link', 'Unlink', 'ChatDotRound', 'ChatLineRound', 'ChatRound',
  'ChatSquare', 'Message', 'MessageBox', 'Bell', 'BellFilled',
  'Phone', 'PhoneFilled', 'Headset', 'Service', 'CustomerService',
  'Guide', 'Compass', 'InfoFilled', 'QuestionFilled', 'WarnTriangleFilled',
  'CircleCheckFilled', 'CircleCloseFilled', 'SuccessFilled', 'WarningFilled',
  'House', 'HomeFilled', 'School', 'Office', 'Coordinate', 'MapLocation',
  'Place', 'FirstAidKit', 'Medicine', 'MagicStick', 'Lightning',
  'Sunny', 'Cloudy', 'PartlyCloudy', 'Overcast', 'Drizzling',
  'Raining', 'Storm', 'Hail', 'Snowing', 'WindPower',
  'Umbrella', 'Basketball', 'Football', 'Soccer', 'Baseball',
  'Bicycle', 'Ship', 'Truck', 'Van', 'Car',
  'Train', 'Airplane', 'Eleme', 'ElemeFilled', 'Platform',
  'Cpu', 'Printer', 'Camera', 'CameraFilled', 'Picture',
  'PictureFilled', 'PictureRounded', 'AlarmClock', 'Clock', 'Watch',
  'Timer', 'Calendar', 'CalendarFilled', 'Notebook', 'Reading',
  'ReadingLamp', 'Paperclip', 'Ticket', 'Stamp', 'Postcard',
  'MailBox', 'Briefcase', 'Suitcase', 'Handbag', 'Key',
  'Lock', 'Unlock', 'VideoCamera', 'VideoCameraFilled', 'Headphones',
  'Microphone', 'MicrophoneFilled', 'Film', 'Headset', 'Mouse',
  'Keyboard', 'Iphone', 'Cellphone', 'Tablet', 'Laptop',
  'Desktop', 'CopyDocument', 'FolderAdd', 'FolderRemove', 'FolderDelete',
  'FolderChecked', 'Tickets', 'DocumentAdd', 'DocumentRemove', 'DocumentDelete',
  'DocumentChecked', 'DocumentCopy', 'Memo', 'ToiletPaper', 'Notebook'
] as const
