/**
 * 主题配置文件
 * 定义支持的主题颜色方案和主题相关配置
 */

/**
 * 主题颜色配置接口
 */
export interface ThemeColors {
  // Element Plus 主色调
  '--el-color-primary': string
  '--el-color-primary-light-3': string
  '--el-color-primary-light-5': string
  '--el-color-primary-light-7': string
  '--el-color-primary-light-8': string
  '--el-color-primary-light-9': string
  '--el-color-primary-dark-2': string

  // 侧边栏背景色
  '--sidebar-bg-color': string
  '--sidebar-text-color': string
  '--sidebar-active-bg': string
  '--sidebar-active-text': string

  // 页面背景色
  '--page-bg-color': string

  // 头部背景色
  '--header-bg-color': string
}

/**
 * 主题配置接口
 */
export interface ThemeConfig {
  /** 主题名称 */
  name: string
  /** 主题标识 */
  key: string
  /** 主题类型：light-亮色, dark-暗色 */
  type: 'light' | 'dark'
  /** 主题颜色配置 */
  colors: ThemeColors
  /** 主题图标 */
  icon?: string
  /** 主题描述 */
  description?: string
}

/**
 * 预定义的主题列表
 */
export const themes: ThemeConfig[] = [
  {
    name: '默认蓝',
    key: 'default',
    type: 'light',
    description: '默认蓝色主题',
    colors: {
      '--el-color-primary': '#4f86f7',
      '--el-color-primary-light-3': '#70a3f5',
      '--el-color-primary-light-5': '#8db9f3',
      '--el-color-primary-light-7': '#a9cef0',
      '--el-color-primary-light-8': '#b8d9f2',
      '--el-color-primary-light-9': '#c6e4f5',
      '--el-color-primary-dark-2': '#3b73e0',
      '--el-color-success': '#67c23a',
      '--el-color-success-light-3': '#95d475',
      '--el-color-success-light-5': '#b3e593',
      '--el-color-success-light-7': '#d1edae',
      '--el-color-success-light-8': '#e2f5c3',
      '--el-color-success-light-9': '#f0f9e1',
      '--el-color-success-dark-2': '#529b2e',
      '--el-color-warning': '#e6a23c',
      '--el-color-warning-light-3': '#f0c78c',
      '--el-color-warning-light-5': '#f5d9b1',
      '--el-color-warning-light-7': '#fae4cc',
      '--el-color-warning-light-8': '#fcebd6',
      '--el-color-warning-light-9': '#fdf4e8',
      '--el-color-warning-dark-2': '#b88230',
      '--el-color-danger': '#f56c6c',
      '--el-color-danger-light-3': '#f89898',
      '--el-color-danger-light-5': '#fab6b6',
      '--el-color-danger-light-7': '#fcd4d4',
      '--el-color-danger-light-8': '#fde3e3',
      '--el-color-danger-light-9': '#fef0f0',
      '--el-color-danger-dark-2': '#c45656',
      '--el-color-error': '#f56c6c',
      '--el-color-error-light-3': '#f89898',
      '--el-color-error-light-5': '#fab6b6',
      '--el-color-error-light-7': '#fcd4d4',
      '--el-color-error-light-8': '#fde3e3',
      '--el-color-error-light-9': '#fef0f0',
      '--el-color-error-dark-2': '#c45656',
      '--el-color-info': '#909399',
      '--el-color-info-light-3': '#b1b3b8',
      '--el-color-info-light-5': '#c8c9cc',
      '--el-color-info-light-7': '#dedfe2',
      '--el-color-info-light-8': '#e9e9eb',
      '--el-color-info-light-9': '#f4f4f5',
      '--el-color-info-dark-2': '#73767a',
      '--el-bg-color': '#ffffff',
      '--el-bg-color-page': '#f2f3f5',
      '--el-bg-color-overlay': '#ffffff',
      '--el-text-color-primary': '#303133',
      '--el-text-color-regular': '#606266',
      '--el-text-color-secondary': '#909399',
      '--el-text-color-placeholder': '#a8abb2',
      '--el-text-color-disabled': '#c0c4cc',
      '--el-border-color': '#dcdfe6',
      '--el-border-color-light': '#e4e7ed',
      '--el-border-color-lighter': '#ebeef5',
      '--el-border-color-extra-light': '#f2f6fc',
      '--el-border-color-dark': '#d4d7de',
      '--el-border-color-darker': '#cdd0d6',
      '--el-fill-color': '#f0f2f5',
      '--el-fill-color-light': '#f5f7fa',
      '--el-fill-color-lighter': '#fafafa',
      '--el-fill-color-extra-light': '#fafcff',
      '--el-fill-color-dark': '#ebedf0',
      '--el-fill-color-darker': '#e6e8eb',
      '--el-fill-color-blank': '#ffffff',
      '--el-box-shadow': '0px 12px 32px 4px rgba(0, 0, 0, 0.04), 0px 8px 20px rgba(0, 0, 0, 0.08)',
      '--el-box-shadow-light': '0px 0px 12px rgba(0, 0, 0, 0.12)',
      '--el-box-shadow-lighter': '0px 0px 6px rgba(0, 0, 0, 0.12)',
      '--el-box-shadow-dark':
        '0px 16px 48px 16px rgba(0, 0, 0, 0.08), 0px 12px 32px rgba(0, 0, 0, 0.12)',
      '--el-overlay-color': 'rgba(0, 0, 0, 0.8)',
      '--el-overlay-color-light': 'rgba(0, 0, 0, 0.7)',
      '--el-overlay-color-lighter': 'rgba(0, 0, 0, 0.5)',
      '--el-mask-color': 'rgba(255, 255, 255, 0.9)',
      '--el-mask-color-extra-light': 'rgba(255, 255, 255, 0.3)',
      '--el-disabled-bg-color': 'var(--el-fill-color-light)',
      '--el-disabled-text-color': 'var(--el-text-color-placeholder)',
      '--el-disabled-border-color': 'var(--el-border-color-light)',
      '--sidebar-bg-color': '#001529',
      '--sidebar-text-color': 'rgba(255,255, 255, 0.85)',
      '--sidebar-active-bg': '#1890ff',
      '--sidebar-active-text': '#ffffff',
      '--page-bg-color': '#f0f2f5',
      '--header-bg-color': '#ffffff',
    },
  },
  {
    name: '天空蓝',
    key: 'sky',
    type: 'light',
    description: '清新的天空蓝色主题',
    colors: {
      '--el-color-primary': '#2b7cff',
      '--el-color-primary-light-3': '#5a99ff',
      '--el-color-primary-light-5': '#7cb5ff',
      '--el-color-primary-light-7': '#9dd0ff',
      '--el-color-primary-light-8': '#aee0ff',
      '--el-color-primary-light-9': '#c1efff',
      '--el-color-primary-dark-2': '#225ecf',
      '--el-color-success': '#67c23a',
      '--el-color-success-light-3': '#95d475',
      '--el-color-success-light-5': '#b3e593',
      '--el-color-success-light-7': '#d1edae',
      '--el-color-success-light-8': '#e2f5c3',
      '--el-color-success-light-9': '#f0f9e1',
      '--el-color-success-dark-2': '#529b2e',
      '--el-color-warning': '#e6a23c',
      '--el-color-warning-light-3': '#f0c78c',
      '--el-color-warning-light-5': '#f5d9b1',
      '--el-color-warning-light-7': '#fae4cc',
      '--el-color-warning-light-8': '#fcebd6',
      '--el-color-warning-light-9': '#fdf4e8',
      '--el-color-warning-dark-2': '#b88230',
      '--el-color-danger': '#f56c6c',
      '--el-color-danger-light-3': '#f89898',
      '--el-color-danger-light-5': '#fab6b6',
      '--el-color-danger-light-7': '#fcd4d4',
      '--el-color-danger-light-8': '#fde3e3',
      '--el-color-danger-light-9': '#fef0f0',
      '--el-color-danger-dark-2': '#c45656',
      '--el-color-error': '#f56c6c',
      '--el-color-error-light-3': '#f89898',
      '--el-color-error-light-5': '#fab6b6',
      '--el-color-error-light-7': '#fcd4d4',
      '--el-color-error-light-8': '#fde3e3',
      '--el-color-error-light-9': '#fef0f0',
      '--el-color-error-dark-2': '#c45656',
      '--el-color-info': '#909399',
      '--el-color-info-light-3': '#b1b3b8',
      '--el-color-info-light-5': '#c8c9cc',
      '--el-color-info-light-7': '#dedfe2',
      '--el-color-info-light-8': '#e9e9eb',
      '--el-color-info-light-9': '#f4f4f5',
      '--el-color-info-dark-2': '#73767a',
      '--el-bg-color': '#ffffff',
      '--el-bg-color-page': '#ffffff',
      '--el-bg-color-overlay': '#ffffff',
      '--el-text-color-primary': '#303133',
      '--el-text-color-regular': '#606266',
      '--el-text-color-secondary': '#909399',
      '--el-text-color-placeholder': '#a8abb2',
      '--el-text-color-disabled': '#c0c4cc',
      '--el-border-color': '#dcdfe6',
      '--el-border-color-light': '#e4e7ed',
      '--el-border-color-lighter': '#ebeef5',
      '--el-border-color-extra-light': '#f2f6fc',
      '--el-border-color-dark': '#d4d7de',
      '--el-border-color-darker': '#cdd0d6',
      '--el-fill-color': '#f0f5ff',
      '--el-fill-color-light': '#f5f8ff',
      '--el-fill-color-lighter': '#fafbff',
      '--el-fill-color-extra-light': '#fafffe',
      '--el-fill-color-dark': '#e9f0ff',
      '--el-fill-color-darker': '#e2ebff',
      '--el-fill-color-blank': '#ffffff',
      '--el-box-shadow': '0px 12px 32px 4px rgba(0, 0, 0, 0.04), 0px 8px 20px rgba(0, 0, 0, 0.08)',
      '--el-box-shadow-light': '0px 0px 12px rgba(0, 0, 0, 0.12)',
      '--el-box-shadow-lighter': '0px 0px 6px rgba(0, 0, 0, 0.12)',
      '--el-box-shadow-dark':
        '0px 16px 48px 16px rgba(0, 0, 0, 0.08), 0px 12px 32px rgba(0, 0, 0, 0.12)',
      '--el-overlay-color': 'rgba(0, 0, 0, 0.8)',
      '--el-overlay-color-light': 'rgba(0, 0, 0, 0.7)',
      '--el-overlay-color-lighter': 'rgba(0, 0, 0, 0.5)',
      '--el-mask-color': 'rgba(255, 255, 255, 0.9)',
      '--el-mask-color-extra-light': 'rgba(255, 255, 255, 0.3)',
      '--el-disabled-bg-color': 'var(--el-fill-color-light)',
      '--el-disabled-text-color': 'var(--el-text-color-placeholder)',
      '--el-disabled-border-color': 'var(--el-border-color-light)',
      '--sidebar-bg-color': '#0a1a3a',
      '--sidebar-text-color': 'rgba(255,255,255, 0.85)',
      '--sidebar-active-bg': '#2b7cff',
      '--sidebar-active-text': '#ffffff',
      '--page-bg-color': '#f0f5ff',
      '--header-bg-color': '#ffffff',
    },
  },
  {
    name: '翡翠绿',
    key: 'emerald',
    type: 'light',
    description: '自然清新的翡翠绿色主题',
    colors: {
      '--el-color-primary': '#6bd16e',
      '--el-color-primary-light-3': '#8be090',
      '--el-color-primary-light-5': '#a7ebab',
      '--el-color-primary-light-7': '#c2f5c5',
      '--el-color-primary-light-8': '#d3f9d8',
      '--el-color-primary-light-9': '#e4fcda',
      '--el-color-primary-dark-2': '#56a858',
      '--el-color-success': '#67c23a',
      '--el-color-success-light-3': '#95d475',
      '--el-color-success-light-5': '#b3e593',
      '--el-color-success-light-7': '#d1edae',
      '--el-color-success-light-8': '#e2f5c3',
      '--el-color-success-light-9': '#f0f9e1',
      '--el-color-success-dark-2': '#529b2e',
      '--el-color-warning': '#e6a23c',
      '--el-color-warning-light-3': '#f0c78c',
      '--el-color-warning-light-5': '#f5d9b1',
      '--el-color-warning-light-7': '#fae4cc',
      '--el-color-warning-light-8': '#fcebd6',
      '--el-color-warning-light-9': '#fdf4e8',
      '--el-color-warning-dark-2': '#b88230',
      '--el-color-danger': '#f56c6c',
      '--el-color-danger-light-3': '#f89898',
      '--el-color-danger-light-5': '#fab6b6',
      '--el-color-danger-light-7': '#fcd4d4',
      '--el-color-danger-light-8': '#fde3e3',
      '--el-color-danger-light-9': '#fef0f0',
      '--el-color-danger-dark-2': '#c45656',
      '--el-color-error': '#f56c6c',
      '--el-color-error-light-3': '#f89898',
      '--el-color-error-light-5': '#fab6b6',
      '--el-color-error-light-7': '#fcd4d4',
      '--el-color-error-light-8': '#fde3e3',
      '--el-color-error-light-9': '#fef0f0',
      '--el-color-error-dark-2': '#c45656',
      '--el-color-info': '#909399',
      '--el-color-info-light-3': '#b1b3b8',
      '--el-color-info-light-5': '#c8c9cc',
      '--el-color-info-light-7': '#dedfe2',
      '--el-color-info-light-8': '#e9e9eb',
      '--el-color-info-light-9': '#f4f4f5',
      '--el-color-info-dark-2': '#73767a',
      '--el-bg-color': '#ffffff',
      '--el-bg-color-page': '#f0fff4',
      '--el-bg-color-overlay': '#ffffff',
      '--el-text-color-primary': '#303133',
      '--el-text-color-regular': '#606266',
      '--el-text-color-secondary': '#909399',
      '--el-text-color-placeholder': '#a8abb2',
      '--el-text-color-disabled': '#c0c4cc',
      '--el-border-color': '#dcdfe6',
      '--el-border-color-light': '#e4e7ed',
      '--el-border-color-lighter': '#ebeef5',
      '--el-border-color-extra-light': '#f2f6fc',
      '--el-border-color-dark': '#d4d7de',
      '--el-border-color-darker': '#cdd0d6',
      '--el-fill-color': '#f0fff4',
      '--el-fill-color-light': '#f5fff9',
      '--el-fill-color-lighter': '#fafffd',
      '--el-fill-color-extra-light': '#fffaff',
      '--el-fill-color-dark': '#e9fff4',
      '--el-fill-color-darker': '#e2fff3',
      '--el-fill-color-blank': '#ffffff',
      '--el-box-shadow': '0px 12px 32px 4px rgba(0, 0, 0, 0.04), 0px 8px 20px rgba(0, 0, 0, 0.08)',
      '--el-box-shadow-light': '0px 0px 12px rgba(0, 0, 0, 0.12)',
      '--el-box-shadow-lighter': '0px 0px 6px rgba(0, 0, 0, 0.12)',
      '--el-box-shadow-dark':
        '0px 16px 48px 16px rgba(0, 0, 0, 0.08), 0px 12px 32px rgba(0, 0, 0, 0.12)',
      '--el-overlay-color': 'rgba(0, 0, 0, 0.8)',
      '--el-overlay-color-light': 'rgba(0, 0, 0, 0.7)',
      '--el-overlay-color-lighter': 'rgba(0, 0, 0, 0.5)',
      '--el-mask-color': 'rgba(255, 255, 255, 0.9)',
      '--el-mask-color-extra-light': 'rgba(255, 255, 255, 0.3)',
      '--el-disabled-bg-color': 'var(--el-fill-color-light)',
      '--el-disabled-text-color': 'var(--el-text-color-placeholder)',
      '--el-disabled-border-color': 'var(--el-border-color-light)',
      '--sidebar-bg-color': '#002814',
      '--sidebar-text-color': 'rgba(255,255,255, 0.85)',
      '--sidebar-active-bg': '#6bd16e',
      '--sidebar-active-text': '#ffffff',
      '--page-bg-color': '#f0fff4',
      '--header-bg-color': '#ffffff',
    },
  },
  {
    name: '活力橙',
    key: 'orange',
    type: 'light',
    description: '充满活力的橙色主题',
    colors: {
      '--el-color-primary': '#ffb366',
      '--el-color-primary-light-3': '#ffc788',
      '--el-color-primary-light-5': '#ffdbaa',
      '--el-color-primary-light-7': '#ffeccc',
      '--el-color-primary-light-8': '#fff2dd',
      '--el-color-primary-light-9': '#fff7ee',
      '--el-color-primary-dark-2': '#cc904f',
      '--el-color-success': '#67c23a',
      '--el-color-success-light-3': '#95d475',
      '--el-color-success-light-5': '#b3e593',
      '--el-color-success-light-7': '#d1edae',
      '--el-color-success-light-8': '#e2f5c3',
      '--el-color-success-light-9': '#f0f9e1',
      '--el-color-success-dark-2': '#529b2e',
      '--el-color-warning': '#e6a23c',
      '--el-color-warning-light-3': '#f0c78c',
      '--el-color-warning-light-5': '#f5d9b1',
      '--el-color-warning-light-7': '#fae4cc',
      '--el-color-warning-light-8': '#fcebd6',
      '--el-color-warning-light-9': '#fdf4e8',
      '--el-color-warning-dark-2': '#b88230',
      '--el-color-danger': '#f56c6c',
      '--el-color-danger-light-3': '#f89898',
      '--el-color-danger-light-5': '#fab6b6',
      '--el-color-danger-light-7': '#fcd4d4',
      '--el-color-danger-light-8': '#fde3e3',
      '--el-color-danger-light-9': '#fef0f0',
      '--el-color-danger-dark-2': '#c45656',
      '--el-color-error': '#f56c6c',
      '--el-color-error-light-3': '#f89898',
      '--el-color-error-light-5': '#fab6b6',
      '--el-color-error-light-7': '#fcd4d4',
      '--el-color-error-light-8': '#fde3e3',
      '--el-color-error-light-9': '#fef0f0',
      '--el-color-error-dark-2': '#c45656',
      '--el-color-info': '#909399',
      '--el-color-info-light-3': '#b1b3b8',
      '--el-color-info-light-5': '#c8c9cc',
      '--el-color-info-light-7': '#dedfe2',
      '--el-color-info-light-8': '#e9e9eb',
      '--el-color-info-light-9': '#f4f4f5',
      '--el-color-info-dark-2': '#73767a',
      '--el-bg-color': '#ffffff',
      '--el-bg-color-page': '#ffffff',
      '--el-bg-color-overlay': '#ffffff',
      '--el-text-color-primary': '#303133',
      '--el-text-color-regular': '#606266',
      '--el-text-color-secondary': '#909399',
      '--el-text-color-placeholder': '#a8abb2',
      '--el-text-color-disabled': '#c0c4cc',
      '--el-border-color': '#dcdfe6',
      '--el-border-color-light': '#e4e7ed',
      '--el-border-color-lighter': '#ebeef5',
      '--el-border-color-extra-light': '#f2f6fc',
      '--el-border-color-dark': '#d4d7de',
      '--el-border-color-darker': '#cdd0d6',
      '--el-fill-color': '#fff7e6',
      '--el-fill-color-light': '#fffbe8',
      '--el-fill-color-lighter': '#fffefb',
      '--el-fill-color-extra-light': '#fffffe',
      '--el-fill-color-dark': '#ffeecc',
      '--el-fill-color-darker': '#ffe6b3',
      '--el-fill-color-blank': '#ffffff',
      '--el-box-shadow': '0px 12px 32px 4px rgba(0, 0, 0, 0.04), 0px 8px 20px rgba(0, 0, 0, 0.08)',
      '--el-box-shadow-light': '0px 0px 12px rgba(0, 0, 0, 0.12)',
      '--el-box-shadow-lighter': '0px 0px 6px rgba(0, 0, 0, 0.12)',
      '--el-box-shadow-dark':
        '0px 16px 48px 16px rgba(0, 0, 0, 0.08), 0px 12px 32px rgba(0, 0, 0, 0.12)',
      '--el-overlay-color': 'rgba(0, 0, 0, 0.8)',
      '--el-overlay-color-light': 'rgba(0, 0, 0, 0.7)',
      '--el-overlay-color-lighter': 'rgba(0, 0, 0, 0.5)',
      '--el-mask-color': 'rgba(255, 255, 255, 0.9)',
      '--el-mask-color-extra-light': 'rgba(255, 255, 255, 0.3)',
      '--el-disabled-bg-color': 'var(--el-fill-color-light)',
      '--el-disabled-text-color': 'var(--el-text-color-placeholder)',
      '--el-disabled-border-color': 'var(--el-border-color-light)',
      '--sidebar-bg-color': '#2f1a00',
      '--sidebar-text-color': 'rgba(255,255,255, 0.85)',
      '--sidebar-active-bg': '#ffb366',
      '--sidebar-active-text': '#ffffff',
      '--page-bg-color': '#fff7e6',
      '--header-bg-color': '#ffffff',
    },
  },
  {
    name: '樱花粉',
    key: 'pink',
    type: 'light',
    description: '温柔浪漫的粉色主题',
    colors: {
      '--el-color-primary': '#f055a0',
      '--el-color-primary-light-3': '#f477b7',
      '--el-color-primary-light-5': '#f899ce',
      '--el-color-primary-light-7': '#fabbe5',
      '--el-color-primary-light-8': '#fccce9',
      '--el-color-primary-light-9': '#fddef2',
      '--el-color-primary-dark-2': '#c04480',
      '--el-color-success': '#67c23a',
      '--el-color-success-light-3': '#95d475',
      '--el-color-success-light-5': '#b3e593',
      '--el-color-success-light-7': '#d1edae',
      '--el-color-success-light-8': '#e2f5c3',
      '--el-color-success-light-9': '#f0f9e1',
      '--el-color-success-dark-2': '#529b2e',
      '--el-color-warning': '#e6a23c',
      '--el-color-warning-light-3': '#f0c78c',
      '--el-color-warning-light-5': '#f5d9b1',
      '--el-color-warning-light-7': '#fae4cc',
      '--el-color-warning-light-8': '#fcebd6',
      '--el-color-warning-light-9': '#fdf4e8',
      '--el-color-warning-dark-2': '#b88230',
      '--el-color-danger': '#f56c6c',
      '--el-color-danger-light-3': '#f89898',
      '--el-color-danger-light-5': '#fab6b6',
      '--el-color-danger-light-7': '#fcd4d4',
      '--el-color-danger-light-8': '#fde3e3',
      '--el-color-danger-light-9': '#fef0f0',
      '--el-color-danger-dark-2': '#c45656',
      '--el-color-error': '#f56c6c',
      '--el-color-error-light-3': '#f89898',
      '--el-color-error-light-5': '#fab6b6',
      '--el-color-error-light-7': '#fcd4d4',
      '--el-color-error-light-8': '#fde3e3',
      '--el-color-error-light-9': '#fef0f0',
      '--el-color-error-dark-2': '#c45656',
      '--el-color-info': '#909399',
      '--el-color-info-light-3': '#b1b3b8',
      '--el-color-info-light-5': '#c8c9cc',
      '--el-color-info-light-7': '#dedfe2',
      '--el-color-info-light-8': '#e9e9eb',
      '--el-color-info-light-9': '#f4f4f5',
      '--el-color-info-dark-2': '#73767a',
      '--el-bg-color': '#ffffff',
      '--el-bg-color-page': '#ffffff',
      '--el-bg-color-overlay': '#ffffff',
      '--el-text-color-primary': '#303133',
      '--el-text-color-regular': '#606266',
      '--el-text-color-secondary': '#909399',
      '--el-text-color-placeholder': '#a8abb2',
      '--el-text-color-disabled': '#c0c4cc',
      '--el-border-color': '#dcdfe6',
      '--el-border-color-light': '#e4e7ed',
      '--el-border-color-lighter': '#ebeef5',
      '--el-border-color-extra-light': '#f2f6fc',
      '--el-border-color-dark': '#d4d7de',
      '--el-border-color-darker': '#cdd0d6',
      '--el-fill-color': '#fff0f8',
      '--el-fill-color-light': '#fff5fc',
      '--el-fill-color-lighter': '#fff9fe',
      '--el-fill-color-extra-light': '#fffbff',
      '--el-fill-color-dark': '#ffe1f3',
      '--el-fill-color-darker': '#ffd2ed',
      '--el-fill-color-blank': '#ffffff',
      '--el-box-shadow': '0px 12px 32px 4px rgba(0, 0, 0, 0.04), 0px 8px 20px rgba(0, 0, 0, 0.08)',
      '--el-box-shadow-light': '0px 0px 12px rgba(0, 0, 0, 0.12)',
      '--el-box-shadow-lighter': '0px 0px 6px rgba(0, 0, 0, 0.12)',
      '--el-box-shadow-dark':
        '0px 16px 48px 16px rgba(0, 0, 0, 0.08), 0px 12px 32px rgba(0, 0, 0, 0.12)',
      '--el-overlay-color': 'rgba(0, 0, 0, 0.8)',
      '--el-overlay-color-light': 'rgba(0, 0, 0, 0.7)',
      '--el-overlay-color-lighter': 'rgba(0, 0, 0, 0.5)',
      '--el-mask-color': 'rgba(255, 255, 255, 0.9)',
      '--el-mask-color-extra-light': 'rgba(255, 255, 255, 0.3)',
      '--el-disabled-bg-color': 'var(--el-fill-color-light)',
      '--el-disabled-text-color': 'var(--el-text-color-placeholder)',
      '--el-disabled-border-color': 'var(--el-border-color-light)',
      '--sidebar-bg-color': '#2f0023',
      '--sidebar-text-color': 'rgba(255,255,255, 0.85)',
      '--sidebar-active-bg': '#f055a0',
      '--sidebar-active-text': '#ffffff',
      '--page-bg-color': '#fff0f8',
      '--header-bg-color': '#ffffff',
    },
  },
  {
    name: '极简灰',
    key: 'gray',
    type: 'light',
    description: '低调优雅的灰色主题',
    colors: {
      '--el-color-primary': '#6e6e6e',
      '--el-color-primary-light-3': '#919191',
      '--el-color-primary-light-5': '#b4b4b4',
      '--el-color-primary-light-7': '#d7d7d7',
      '--el-color-primary-light-8': '#e3e3e3',
      '--el-color-primary-light-9': '#efefef',
      '--el-color-primary-dark-2': '#585858',
      '--el-color-success': '#67c23a',
      '--el-color-success-light-3': '#95d475',
      '--el-color-success-light-5': '#b3e593',
      '--el-color-success-light-7': '#d1edae',
      '--el-color-success-light-8': '#e2f5c3',
      '--el-color-success-light-9': '#f0f9e1',
      '--el-color-success-dark-2': '#529b2e',
      '--el-color-warning': '#e6a23c',
      '--el-color-warning-light-3': '#f0c78c',
      '--el-color-warning-light-5': '#f5d9b1',
      '--el-color-warning-light-7': '#fae4cc',
      '--el-color-warning-light-8': '#fcebd6',
      '--el-color-warning-light-9': '#fdf4e8',
      '--el-color-warning-dark-2': '#b88230',
      '--el-color-danger': '#f56c6c',
      '--el-color-danger-light-3': '#f89898',
      '--el-color-danger-light-5': '#fab6b6',
      '--el-color-danger-light-7': '#fcd4d4',
      '--el-color-danger-light-8': '#fde3e3',
      '--el-color-danger-light-9': '#fef0f0',
      '--el-color-danger-dark-2': '#c45656',
      '--el-color-error': '#f56c6c',
      '--el-color-error-light-3': '#f89898',
      '--el-color-error-light-5': '#fab6b6',
      '--el-color-error-light-7': '#fcd4d4',
      '--el-color-error-light-8': '#fde3e3',
      '--el-color-error-light-9': '#fef0f0',
      '--el-color-error-dark-2': '#c45656',
      '--el-color-info': '#909399',
      '--el-color-info-light-3': '#b1b3b8',
      '--el-color-info-light-5': '#c8c9cc',
      '--el-color-info-light-7': '#dedfe2',
      '--el-color-info-light-8': '#e9e9eb',
      '--el-color-info-light-9': '#f4f4f5',
      '--el-color-info-dark-2': '#73767a',
      '--el-bg-color': '#ffffff',
      '--el-bg-color-page': '#ffffff',
      '--el-bg-color-overlay': '#ffffff',
      '--el-text-color-primary': '#303133',
      '--el-text-color-regular': '#606266',
      '--el-text-color-secondary': '#909399',
      '--el-text-color-placeholder': '#a8abb2',
      '--el-text-color-disabled': '#c0c4cc',
      '--el-border-color': '#dcdfe6',
      '--el-border-color-light': '#e4e7ed',
      '--el-border-color-lighter': '#ebeef5',
      '--el-border-color-extra-light': '#f2f6fc',
      '--el-border-color-dark': '#d4d7de',
      '--el-border-color-darker': '#cdd0d6',
      '--el-fill-color': '#f5f5f5',
      '--el-fill-color-light': '#fafafa',
      '--el-fill-color-lighter': '#ffffff',
      '--el-fill-color-extra-light': '#ffffff',
      '--el-fill-color-dark': '#ebebeb',
      '--el-fill-color-darker': '#e0e0e0',
      '--el-fill-color-blank': '#ffffff',
      '--el-box-shadow': '0px 12px 32px 4px rgba(0, 0, 0, 0.04), 0px 8px 20px rgba(0, 0, 0, 0.08)',
      '--el-box-shadow-light': '0px 0px 12px rgba(0, 0, 0, 0.12)',
      '--el-box-shadow-lighter': '0px 0px 6px rgba(0, 0, 0, 0.12)',
      '--el-box-shadow-dark':
        '0px 16px 48px 16px rgba(0, 0, 0, 0.08), 0px 12px 32px rgba(0, 0, 0, 0.12)',
      '--el-overlay-color': 'rgba(0, 0, 0, 0.8)',
      '--el-overlay-color-light': 'rgba(0, 0, 0, 0.7)',
      '--el-overlay-color-lighter': 'rgba(0, 0, 0, 0.5)',
      '--el-mask-color': 'rgba(255, 255, 255, 0.9)',
      '--el-mask-color-extra-light': 'rgba(255, 255, 255, 0.3)',
      '--el-disabled-bg-color': 'var(--el-fill-color-light)',
      '--el-disabled-text-color': 'var(--el-text-color-placeholder)',
      '--el-disabled-border-color': 'var(--el-border-color-light)',
      '--sidebar-bg-color': '#1f1f1f',
      '--sidebar-text-color': 'rgba(255,255,255, 0.85)',
      '--sidebar-active-bg': '#6e6e6e',
      '--sidebar-active-text': '#ffffff',
      '--page-bg-color': '#f5f5f5',
      '--header-bg-color': '#ffffff',
    },
  },
  {
    name: '深紫',
    key: 'purple',
    type: 'light',
    description: '神秘高贵的紫色主题',
    colors: {
      '--el-color-primary': '#8645e6',
      '--el-color-primary-light-3': '#a46aeb',
      '--el-color-primary-light-5': '#c28ff0',
      '--el-color-primary-light-7': '#e094f5',
      '--el-color-primary-light-8': '#eda7fa',
      '--el-color-primary-light-9': '#f5b9ff',
      '--el-color-primary-dark-2': '#6b37b8',
      '--el-color-success': '#67c23a',
      '--el-color-success-light-3': '#95d475',
      '--el-color-success-light-5': '#b3e593',
      '--el-color-success-light-7': '#d1edae',
      '--el-color-success-light-8': '#e2f5c3',
      '--el-color-success-light-9': '#f0f9e1',
      '--el-color-success-dark-2': '#529b2e',
      '--el-color-warning': '#e6a23c',
      '--el-color-warning-light-3': '#f0c78c',
      '--el-color-warning-light-5': '#f5d9b1',
      '--el-color-warning-light-7': '#fae4cc',
      '--el-color-warning-light-8': '#fcebd6',
      '--el-color-warning-light-9': '#fdf4e8',
      '--el-color-warning-dark-2': '#b88230',
      '--el-color-danger': '#f56c6c',
      '--el-color-danger-light-3': '#f89898',
      '--el-color-danger-light-5': '#fab6b6',
      '--el-color-danger-light-7': '#fcd4d4',
      '--el-color-danger-light-8': '#fde3e3',
      '--el-color-danger-light-9': '#fef0f0',
      '--el-color-danger-dark-2': '#c45656',
      '--el-color-error': '#f56c6c',
      '--el-color-error-light-3': '#f89898',
      '--el-color-error-light-5': '#fab6b6',
      '--el-color-error-light-7': '#fcd4d4',
      '--el-color-error-light-8': '#fde3e3',
      '--el-color-error-light-9': '#fef0f0',
      '--el-color-error-dark-2': '#c45656',
      '--el-color-info': '#909399',
      '--el-color-info-light-3': '#b1b3b8',
      '--el-color-info-light-5': '#c8c9cc',
      '--el-color-info-light-7': '#dedfe2',
      '--el-color-info-light-8': '#e9e9eb',
      '--el-color-info-light-9': '#f4f4f5',
      '--el-color-info-dark-2': '#73767a',
      '--el-bg-color': '#ffffff',
      '--el-bg-color-page': '#ffffff',
      '--el-bg-color-overlay': '#ffffff',
      '--el-text-color-primary': '#303133',
      '--el-text-color-regular': '#606266',
      '--el-text-color-secondary': '#909399',
      '--el-text-color-placeholder': '#a8abb2',
      '--el-text-color-disabled': '#c0c4cc',
      '--el-border-color': '#dcdfe6',
      '--el-border-color-light': '#e4e7ed',
      '--el-border-color-lighter': '#ebeef5',
      '--el-border-color-extra-light': '#f2f6fc',
      '--el-border-color-dark': '#d4d7de',
      '--el-border-color-darker': '#cdd0d6',
      '--el-fill-color': '#f9f0ff',
      '--el-fill-color-light': '#fbf5ff',
      '--el-fill-color-lighter': '#fdfaff',
      '--el-fill-color-extra-light': '#feffff',
      '--el-fill-color-dark': '#f0e4ff',
      '--el-fill-color-darker': '#e8d8ff',
      '--el-fill-color-blank': '#ffffff',
      '--el-box-shadow': '0px 12px 32px 4px rgba(0, 0, 0, 0.04), 0px 8px 20px rgba(0, 0, 0, 0.08)',
      '--el-box-shadow-light': '0px 0px 12px rgba(0, 0, 0, 0.12)',
      '--el-box-shadow-lighter': '0px 0px 6px rgba(0, 0, 0, 0.12)',
      '--el-box-shadow-dark':
        '0px 16px 48px 16px rgba(0, 0, 0, 0.08), 0px 12px 32px rgba(0, 0, 0, 0.12)',
      '--el-overlay-color': 'rgba(0, 0, 0, 0.8)',
      '--el-overlay-color-light': 'rgba(0, 0, 0, 0.7)',
      '--el-overlay-color-lighter': 'rgba(0, 0, 0, 0.5)',
      '--el-mask-color': 'rgba(255, 255, 255, 0.9)',
      '--el-mask-color-extra-light': 'rgba(255, 255, 255, 0.3)',
      '--el-disabled-bg-color': 'var(--el-fill-color-light)',
      '--el-disabled-text-color': 'var(--el-text-color-placeholder)',
      '--el-disabled-border-color': 'var(--el-border-color-light)',
      '--sidebar-bg-color': '#120338',
      '--sidebar-text-color': 'rgba(255,255,255, 0.85)',
      '--sidebar-active-bg': '#8645e6',
      '--sidebar-active-text': '#ffffff',
      '--page-bg-color': '#f9f0ff',
      '--header-bg-color': '#ffffff',
    },
  },
  {
    name: '纯净白',
    key: 'white',
    type: 'light',
    description: '简洁明快的纯净白色主题',
    colors: {
      '--el-color-primary': '#3d91ff',
      '--el-color-primary-light-3': '#6aa8ff',
      '--el-color-primary-light-5': '#97beff',
      '--el-color-primary-light-7': '#c4d4ff',
      '--el-color-primary-light-8': '#d3e2ff',
      '--el-color-primary-light-9': '#e2efff',
      '--el-color-primary-dark-2': '#3174cc',
      '--el-color-success': '#67c23a',
      '--el-color-success-light-3': '#95d475',
      '--el-color-success-light-5': '#b3e593',
      '--el-color-success-light-7': '#d1edae',
      '--el-color-success-light-8': '#e2f5c3',
      '--el-color-success-light-9': '#f0f9e1',
      '--el-color-success-dark-2': '#529b2e',
      '--el-color-warning': '#e6a23c',
      '--el-color-warning-light-3': '#f0c78c',
      '--el-color-warning-light-5': '#f5d9b1',
      '--el-color-warning-light-7': '#fae4cc',
      '--el-color-warning-light-8': '#fcebd6',
      '--el-color-warning-light-9': '#fdf4e8',
      '--el-color-warning-dark-2': '#b88230',
      '--el-color-danger': '#f56c6c',
      '--el-color-danger-light-3': '#f89898',
      '--el-color-danger-light-5': '#fab6b6',
      '--el-color-danger-light-7': '#fcd4d4',
      '--el-color-danger-light-8': '#fde3e3',
      '--el-color-danger-light-9': '#fef0f0',
      '--el-color-danger-dark-2': '#c45656',
      '--el-color-error': '#f56c6c',
      '--el-color-error-light-3': '#f89898',
      '--el-color-error-light-5': '#fab6b6',
      '--el-color-error-light-7': '#fcd4d4',
      '--el-color-error-light-8': '#fde3e3',
      '--el-color-error-light-9': '#fef0f0',
      '--el-color-error-dark-2': '#c45656',
      '--el-color-info': '#909399',
      '--el-color-info-light-3': '#b1b3b8',
      '--el-color-info-light-5': '#c8c9cc',
      '--el-color-info-light-7': '#dedfe2',
      '--el-color-info-light-8': '#e9e9eb',
      '--el-color-info-light-9': '#f4f4f5',
      '--el-color-info-dark-2': '#73767a',
      '--el-bg-color': '#ffffff',
      '--el-bg-color-page': '#ffffff',
      '--el-bg-color-overlay': '#ffffff',
      '--el-text-color-primary': '#1a1a1a',
      '--el-text-color-regular': '#4d4d4d',
      '--el-text-color-secondary': '#737373',
      '--el-text-color-placeholder': '#999999',
      '--el-text-color-disabled': '#bfbfbf',
      '--el-border-color': '#e6e6e6',
      '--el-border-color-light': '#ececec',
      '--el-border-color-lighter': '#f2f2f2',
      '--el-border-color-extra-light': '#f8f8f8',
      '--el-border-color-dark': '#d0d0d0',
      '--el-border-color-darker': '#bababa',
      '--el-fill-color': '#f8f9fa',
      '--el-fill-color-light': '#ffffff',
      '--el-fill-color-lighter': '#ffffff',
      '--el-fill-color-extra-light': '#ffffff',
      '--el-fill-color-dark': '#f0f1f2',
      '--el-fill-color-darker': '#e9ecef',
      '--el-fill-color-blank': '#ffffff',
      '--el-box-shadow': '0px 2px 8px rgba(0, 0, 0, 0.06), 0px 1px 4px rgba(0, 0, 0, 0.03)',
      '--el-box-shadow-light': '0px 0px 4px rgba(0, 0, 0, 0.06)',
      '--el-box-shadow-lighter': '0px 0px 2px rgba(0, 0, 0, 0.06)',
      '--el-box-shadow-dark': '0px 4px 12px rgba(0, 0, 0, 0.06), 0px 2px 6px rgba(0, 0, 0, 0.03)',
      '--el-overlay-color': 'rgba(0, 0, 0, 0.4)',
      '--el-overlay-color-light': 'rgba(0, 0, 0, 0.3)',
      '--el-overlay-color-lighter': 'rgba(0, 0, 0, 0.2)',
      '--el-mask-color': 'rgba(0, 0, 0, 0.4)',
      '--el-mask-color-extra-light': 'rgba(0, 0, 0, 0.2)',
      '--el-disabled-bg-color': 'var(--el-fill-color-light)',
      '--el-disabled-text-color': 'var(--el-text-color-placeholder)',
      '--el-disabled-border-color': 'var(--el-border-color-light)',
      '--sidebar-bg-color': '#ffffff',
      '--sidebar-text-color': '#666666',
      '--sidebar-active-bg': '#3d91ff',
      '--sidebar-active-text': '#ffffff',
      '--page-bg-color': '#ffffff',
      '--header-bg-color': '#ffffff',
      '--sidebar-border-color': 'rgba(0, 0, 0, 0.08)',
      '--sidebar-shadow': '1px 0 0 0 rgba(0, 0, 0, 0.04)',
    },
  },
]

/**
 * 默认主题key
 */
export const DEFAULT_THEME_KEY = 'default'

/**
 * 本地存储的主题key
 */
export const THEME_STORAGE_KEY = 'chai-admin-theme'

/**
 * 根据主题key获取主题配置
 * @param themeKey 主题key
 * @returns 主题配置，如果不存在则返回默认主题
 */
export function getThemeByKey(themeKey: string): ThemeConfig {
  return (
    themes.find((theme) => theme.key === themeKey) ||
    themes.find((theme) => theme.key === DEFAULT_THEME_KEY)!
  )
}

/**
 * 判断主题是否为暗色主题
 * @param themeKey 主题key
 * @returns 是否为暗色主题
 */
export function isDarkTheme(themeKey: string): boolean {
  const theme = getThemeByKey(themeKey)
  return theme.type === 'dark'
}

/**
 * 将主题颜色应用到文档
 * @param colors 主题颜色配置
 */
export function applyThemeColors(colors: ThemeColors): void {
  const root = document.documentElement
  Object.entries(colors).forEach(([property, value]) => {
    root.style.setProperty(property, value)
  })
}
